### PR TITLE
Improve classification accuracy and coverage by merging profiles

### PR DESCRIPTION
**Pull request by yanirs**
<strong>Motivation</strong>: This set of changes improves our understanding of how the plugin performs on texts of various lengths and types, and increases the number of supported languages while improving classification accuracy.

<h3>Main changes</h3>

<ul>
<li>Add tests for <code>LangdetectService</code> that evaluate its classification accuracy (percentage of correctly-classified texts) on various text lengths and types. These tests are instantiated dynamically by the <code>DetectLanguageAccuracyTest</code> class using a CSV file (<code>src/test/resources/org/xbib/elasticsearch/index/mapper/langdetect/accuracies.csv</code>), which contains a row for each set of parameters with the expected classification accuracy for each language. The tested parameters include:

<ul>
<li>Text length, with emphasis on short texts in the 5-20 characters range (simulating search queries).</li>
<li>Text type, represented by two new datasets that cover all the languages supported by the plugin: translations of the Universal Declaration of Human Rights (<code>src/test/resources/org/xbib/elasticsearch/index/mapper/langdetect/udhr.tsv</code>), and translations of the WordPress interface (<code>src/test/resources/org/xbib/elasticsearch/index/mapper/langdetect/wordpress-translations.tsv</code>).</li>
<li>Language profile: <code>original-default</code>, <code>short-text</code>, or the newly-added <code>merged-average</code> (more on this below).</li>
<li>Supported languages: <code>original-default</code> or <code>all</code>.</li>
</ul></li>
<li>Add the Python code used to generate the datasets. See <code>scripts/README.md</code> for running instructions.</li>
<li>Add an option to regenerate <code>DetectLanguageAccuracyTest</code>'s CSV input file: When the <code>path.accuracies.out</code> system property is set, the test class writes the accuracies to a CSV file, making it easy to update the expected results if they ever change.</li>
<li>Add <code>merged-average</code>, a new language profile that combines the <code>original-default</code> and <code>short-text</code> profiles by averaging the n-gram frequencies for every language. This language profile supports 55 languages (the union of the 53 languages supported by the <code>original-default</code> profile and the 47 languages supported by the <code>short-text</code> profile), while increasing classification accuracy on the 45 original-default languages (the intersection of the two existing profiles). A comparison of the performance of the different profiles is shown below. Given this comparison, the default settings have been changed to use the <code>merged-average</code> profile on all 55 languages.</li>
<li>Refactor <code>LangProfile</code> to make it immutable and allow it to read <code>long</code> integers.</li>
<li>Normalise Romanian and Vietnamese characters, as done by Shuyo's original library. According to tests on the UDHR and WordPress translations datasets, this improves classification accuracy on these languages, and doesn't affect performance on other languages. Original code for reference:

<ul>
<li>Romanian: <a href="https://github.com/shuyo/language-detection/blob/master/src/com/cybozu/labs/langdetect/util/NGram.java#L81">code</a>, <a href="https://github.com/shuyo/language-detection/blob/master/src/com/cybozu/labs/langdetect/util/NGramTest.java#L101">test</a></li>
<li>Vietnamese: <a href="https://github.com/shuyo/language-detection/blob/master/src/com/cybozu/labs/langdetect/util/NGram.java#L111">code</a>, <a href="https://github.com/shuyo/language-detection/blob/master/src/com/cybozu/labs/langdetect/util/NGramTest.java#L192">test</a></li>
</ul></li>
</ul>

<h3>Summary of experiments</h3>

The following table presents the mean accuracy by dataset, profile, text length (full versus short – texts of length 5, 10 & 20), and language setting. As a reminder, the original number of default languages is 45, while the <code>original-default</code>, <code>merged-average</code>, and <code>short-text</code> profiles support 53, 55, and 47 languages respectively. Therefore, when testing on all languages, two numbers are reported for the <code>original-default</code> and <code>short-text</code> profiles: The first is the mean accuracy across all 55 languages (including languages they can't get right due to lack of support), and the second is  the mean accuracy across only the supported languages (marked with <em>S:</em>). I think that the first number is more in line with the goals of many plugin users, who would want to increase coverage, but can't guarantee that they'd only try to classify texts in supported languages. The second number is provided for completeness.

<table border="1">
  <thead>
    <tr>
      <th>Dataset</th>
      <th>Profile</th>
      <th>Full texts; all 55 languages</th>
      <th>Full texts; original-default 45 languages</th>
      <th>Short texts; all 55 languages</th>
      <th>Short texts; original-default 45 languages</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th rowspan="3" valign="top">udhr</th>
      <th>original-default</th>
      <td>96.36%<br>(S: 100%)</td>
      <td>100%</td>
      <td>75.11%<br>(S: 77.94%)</td>
      <td>81.11%</td>
    </tr>
    <tr>
      <th>merged-average</th>
      <td>100%</td>
      <td>100%</td>
      <td>77.76%</td>
      <td>81.39%</td>
    </tr>
    <tr>
      <th>short-text</th>
      <td>85.45%<br>(S: 100%)</td>
      <td>100%</td>
      <td>68.32%<br>(S: 79.95%)</td>
      <td>80.41%</td>
    </tr>
    <tr style="border-top:10px solid black;">
      <th rowspan="3" valign="top">wordpress-translations</th>
      <th>original-default</th>
      <td>95.45%<br>(S: 99.06%)</td>
      <td>98.93%</td>
      <td>69.55%<br>(S: 72.17%)</td>
      <td>74.95%</td>
    </tr>
    <tr>
      <th>merged-average</th>
      <td>99.60%</td>
      <td>99.69%</td>
      <td>73.43%</td>
      <td>77.25%</td>
    </tr>
    <tr>
      <th>short-text</th>
      <td>85.16%<br>(S: 99.66%)</td>
      <td>99.64%</td>
      <td>65.01%<br>(S: 76.08%)</td>
      <td>76.55%</td>
    </tr>
  </tbody>
</table>

<h3>Manual testing</h3>

<ul>
<li>Run <code>./gradlew test --rerun-tasks --info</code> to view the output of the new tests (all tests should pass).</li>
<li>Run <code>./gradlew test --rerun-tasks -Dpath.accuracies.out=accuracies.csv</code>, and verify that the output <code>accuracies.csv</code> file is identical to <code>src/test/resources/org/xbib/elasticsearch/index/mapper/langdetect/accuracies.csv</code>.</li>
</ul>

### CODE REVIEW

**Comment by yanirs** [comment]
@jprante Any thoughts on this PR? I'm happy to provide more details if necessary. :slightly_smiling_face:

**Comment by jprante** [comment]
@yanirs sorry for the delay. That's simply marvelous work, I'm very impressed. Thank you for sharing your imrpovments with me and the community!

I have to go into the details for myself in a quiet hour, I'm confident from your excellent pull request that everything will work perfectly.

**Comment by yanirs** [comment]
@jprante Thank you! :smile:

**Comment by jprante** [comment]
I have released version 5.4.0.2 with the pull request included.

**Pull request merged**
