### PR TITLE
update to ES 2.4.3

### PR DESCRIPTION
**Pull request by stevekaeser**
I've updated the build.gradle file to build against ES 2.4.3.

### CODE REVIEW

**Comment by GuillaumeDievart** [comment]
@jprante, Any chance to see this PR merged in the next days ?

Thanks !

**Comment by jprante** [comment]
yes, if I find time on the weekend, updates to latest ES releases will be done.

**Comment by GuillaumeDievart** [comment]
@jprante Thanks for your time and your work !

**Comment by jprante** [comment]
I have released plugin versions 2.4.3.0 for ES 2.4.3 and 2.4.4.0 for ES 2.4.4 (in a new 2.4 branch)

**Comment by GuillaumeDievart** [comment]
Thanks !!

**Comment by GuillaumeDievart** [comment]
Hi @jprante,

it's normal that the plugin is not available on this url https://github.com/jprante/elasticsearch-langdetect/releases/download/2.3.3.0/elasticsearch-langdetect-2.4.4.0-plugin.zip ?

I need to build it myself ?

Thanks

**Comment by jprante** [comment]
Try the URL

http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-langdetect/2.4.4.0/elasticsearch-langdetect-2.4.4.0-plugin.zip

**Comment by jprante** [comment]
Closing this pull request.

**Pull request closed without merging**
